---
# packages to be installed alongside i3wm
installs:
  - arandr
  - autojump
  - blueman
  - brightnessctl
  - compton
  - curl
  - feh
  - gitg
  - gtk-chtheme
  - i3
  - i3blocks
  - imagemagick
  - lxappearance
  - pavucontrol
  - qt4-qtconfig
  - rofi
  - scrot
  - ubuntu-desktop  # TODO: Eventually it would be nice to drop this and build a more minimal environment.
  - xautolock
  - xinit
  - zenity

  # This probably needs a separate role.
  # - playerctl
