---

target_user: "{{ansible_user_id}}"
dotfiles_root_path: "/home/{{target_user}}/code/personal"
dotfiles_base_name: "dotfiles"
dotfiles_repo: "https://github.com/ABitMoreDepth/dotfiles.git"
# dotfiles_repo: "git@github.com:ABitMoreDepth/dotfiles.git"
