---

# Play to install and configure Compton

- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Install Compton
      apt:
        name: compton
        state: "present"
        cache_valid_time: 600

    - name: Symlink compton config into place
      file:
        src: "{{dotfiles_base_dir}}/compton/compton.conf"
        dest: "{{config_base_dir}}/compton.conf"
        state: link
        force: yes

