---
# Variables used when setting up tools
user: "{{ansible_user_id}}"
personal_code_base_dir: "/home/{{user}}/code/personal"
dotfiles_base_dir: "{{personal_code_base_dir}}/dotfiles"
python_bin_dir: "/home/{{user}}/.local/bin"
